### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by wesselvdv** [Effect-TS/html#1]
- [x] Make caches global with unsafeMake
- [x] Add renderToString for SSR
- [x] Remove non-standard functionality (`.|@|?|ref|dataset|aria`)
- [x] Expose Many.from as Collection
- [x] Add ref with ElementRef
- [x] Add basic afterRender hook
- [x] Add unit tests for render & renderToString
- [ ] Add support for directives to generalise behaviour for nodes

**Comment by wesselvdv** [comment]
see #2 for the directive support/discussion
